# Generated by Django 6.0.2 on 2026-02-21 14:32

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ls_backend', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicer',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='servicer',
            name='longitude',
        ),
        migrations.AddField(
            model_name='servicer',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326),
        ),
    ]
