# Generated by Django 6.0.2 on 2026-02-21 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ls_backend', '0002_remove_servicer_latitude_remove_servicer_longitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(default='admin', max_length=100),
        ),
    ]
