# Generated by Django 6.0.2 on 2026-02-22 08:02

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ls_backend', '0004_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicer',
            name='category',
            field=models.CharField(choices=[('Hospital', 'Hospital'), ('ATM', 'ATM'), ('Shop', 'Shop'), ('Other', 'Other')], max_length=100),
        ),
        migrations.AlterField(
            model_name='servicer',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, geography=True, null=True, srid=4326),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.CharField(max_length=250, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('public', 'Public')], default='public', max_length=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=250, unique=True),
        ),
        migrations.AddIndex(
            model_name='servicer',
            index=models.Index(fields=['category'], name='ls_backend__categor_8f3c1f_idx'),
        ),
    ]
