# Generated by Django 6.0.2 on 2026-02-22 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ls_backend', '0005_alter_servicer_category_alter_servicer_location_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=250),
        ),
    ]
